---
root: true

extends:
  - "@react-native-community"
  - prettier

plugins:
  - "@react-native-community"
  - "@typescript-eslint"
  - import
  - prettier

rules:
  no-bitwise: 0
  no-return-await: 2
  no-dupe-class-members: 2
  import/default: 2
  import/export: 2
  react-hooks/exhaustive-deps: 0

parser: "@typescript-eslint/parser"
